### PR TITLE
fix: replace tooltip class by ant icon

### LINKED ISSUE #350: info icon at title of `קיום נסיעות` top chart of dashboard not looks clear
image

### PR DESCRIPTION
**Pull request by shootermv**
# Description
closes #350 

## screenshots
image

### CODE REVIEW

File: src/pages/dashboard/AllLineschart/AllLinesChart.tsx [hunk 1]
```diff
@@ -37,7 +38,7 @@ export const AllLinesChart: FC<AllChartComponentProps> = ({ startDate, endDate }
           title={convertLineFeedToHtmlTags(t('dashboard_tooltip_content'))}
           placement="left"
           arrow>
-          <span className="tooltip-icon">i</span>
```
Comment (NoamGaash) [inline src/pages/dashboard/AllLineschart/AllLinesChart.tsx:40]: did you remove the relevant rule from the scss file?

**Review by NoamGaash — APPROVED** [review]

File: src/pages/dashboard/AllLineschart/AllLinesChart.tsx (hunk 1 above)
Comment (shootermv) [reply src/pages/dashboard/AllLineschart/AllLinesChart.tsx:40]: No. My bad. Will remove it asap
