### PR TITLE
fix: time related issues in the "map by line" page

### LINKED ISSUE #902: fix: מפה לפי קו  - לא מוצגות נסיעות לאחר השעה 6 בערב
יש כרגע בעיה עם הממשק בעמוד של [מפה לפי קו](https://open-bus-map-search.hasadna.org.il/single-line-map), הוא לא מציג נסיעות שמתחילות לאחר השעה 6 בערב.

לאחר בדיקה איתרתי את הבאג: הפונקציה [useSingleLineData](https://github.com/hasadna/open-bus-map-search/blob/dd47dc00785bc9f0320884db94729f80fcfbdd46/src/hooks/useSingleLineData.ts#L9) יוצרת זמן התחלה לתחילת היום וזמן סיום עבור הרגע האחרון של היום:

```
const { locations, isLoading: locationsAreLoading } = useVehicleLocations({
    from: +new Date(timestamp).setHours(0, 0, 0, 0),
    to: +new Date(timestamp).setHours(23, 59, 59, 999),
    lineRef,
    splitMinutes: 360,
    pause: !lineRef,
  })
```

הפונקציה [useVehicleLocations](https://github.com/hasadna/open-bus-map-search/blob/dd47dc00785bc9f0320884db94729f80fcfbdd46/src/api/useVehicleLocations.ts#L182) מחלקת את טווח הזמן לחלקים שווים לפי הערך split באמצעות הפונקציה [getMinutesInRange](https://github.com/hasadna/open-bus-map-search/blob/dd47dc00785bc9f0320884db94729f80fcfbdd46/src/api/useVehicleLocations.ts#L151):

```
function getMinutesInRange(from: Dateable, to: Dateable, gap = 1) {
  const start = moment(from).startOf('minute')
  const end = moment(to).startOf('minute')

  // array of minutes to load
  const minutes = Array.from({ length: end.diff(start, 'minutes') / gap }, (_, i) => ({
    from: start.clone().add(i * gap, 'minutes'),
    to: start.clone().add((i + 1) * gap, 'minutes'),
  }))
  return minutes
}
```

הבעיה שנוצרת היא שהקוד:
```
length: end.diff(start, 'minutes') / gap
```
מחזיר במקרה הזה את הערך 3.9972222222222222, אשר מתורגם כנראה בתור ערך מספרי 3, נסה:
```
parseInt(end.diff(start, 'minutes') / gap)
```
זה גורם לכך שנשלחות לשרת בקשות של 3 טווחי זמן של 6 שעות, במקום 4 כפי הנדרש.

יש 2 פתרונות אפשריים, אבל מכיוון שלא חקרתי את כל הקוד אינני יכול להמליץ על אחד מהם, ולכן אני מניח כאן את הדברים במקום לבצע Fork פשוט:

א. לבצע שינוי בפונקציה useSingleLineData כך שערך הסיום יוגדר לשנייה הראשונה של היום הבא, לדוגמא:
```
to: +new Date(timestamp + 24 * 60 * 60 * 1000).setHours(0, 0, 0, 0);
```

ב. לשנות את הפונקציה getMinutesInRange ולהחיל round על תוצאות החלוקה ב-gap (נראה פחות מומלץ, יש לבדוק את ההשלכות על כל מקרי השימוש במרבי הממשק):
```
function getMinutesInRange(from, to, gap = 1) {
  const start = moment(from).startOf('minute')
  const end = moment(to).startOf('minute')

  // array of minutes to load
  const minutes = Array.from({ length: Math.round(end.diff(start, 'minutes') / gap) }, (_, i) => ({
    from: start.clone().add(i * gap, 'minutes'),
    to: start.clone().add((i + 1) * gap, 'minutes'),
  }))
  return minutes
}
```

### PR DESCRIPTION
**Pull request by TomRytt**
# Description

Fixes #902.

Fixes the following issues:
1. Single lines times stopped at 6PM
2. First lines were from 11PM the day before
3. The wrong time was used to filter the times (recorded at times instead of scheduled start time) - which resulted in issue 2.

Optimizations:
1. Optimized the useMemo to return an empty array if no positions passed the filter (typically when no line is chosen yet)
2. Switched to using a Set to ensure times can only appear in options once

## screenshots
image

Taken at 22:58 (two minutes before the next bus is scheduled)
image

Taken at 23:00 (after the bus is scheduled)
image

### CODE REVIEW

File: src/hooks/useSingleLineData.ts [hunk 1]
```diff
@@ -35,17 +37,45 @@ export const useSingleLineData = (lineRef?: number, routeIds?: number[]) => {
     return pos
   }, [locations])
 
+  function convertTo24HourAndToNumber(time: string): number {
```
Comment (NoamGaash) [inline src/hooks/useSingleLineData.ts:40]: The name does not reflect that the output of this method is the number of minutes since midnight. Would you consider renaming this method?
This is my suggestion, but feel free to implement anything you like.
```suggestion
  function timestringToMinutes(time: string): number {
```

**Review by NoamGaash — APPROVED** [review]
Great, thank you very much.
Consider adding tests or adding an issue describing the test cases that would cover this bug to prevent future regressions

**Comment by NoamGaash** [comment]
@TomRytt Thanks for making this effort, I'm not really sure where this PR stands. Can I merge it?  Thank you very much

**Comment by TomRytt** [comment]
> @TomRytt Thanks for making this effort, I'm not really sure where this PR stands. Can I merge it?  Thank you very much


Replying here so it is also documented as we resolved this face to face. After speaking I merged this PR but I am getting notifications that the Pipeline fails, I need to investigate it later today, might require assistance, I'll let you know if I do.

**Comment by NoamGaash** [comment]
Thanks! It's failing because of a test that we should fix - 
https://github.com/hasadna/open-bus-map-search/pull/958#issuecomment-2514118547
I'll address it later today (probably in the evening) by fixing / skipping the problematic test :pray:
